### ISSUE TITLE
Don't load data at import

### ISSUE THREAD

**Issue by xrotwang** [glottobank/clpa#14]
I think it is not a good idea to do too much at import (at least it seems to violate "explicit is better than implicit"). [Here](https://github.com/glottobank/clpa/blob/master/pyclpa/__init__.py#L3), JSON and csv files are parsed, and a rather big object is instantiated. Can't we have a `init` function, and start out with `clpa = None` at import? Or leave the instantiation of the `CLPA` class to calling code entirely?

**Comment by xrotwang** [comment]
Actually, we should just have a function `get_clpa`, which returns the global `pyclpa.clpa` object (instantiating it if not yet done).

**Comment by LinguList** [comment]
yep, I agree. The necessity of loading data only once became evident when testing on single strings, where we would re-load all the json-stuff all the time, so loading data in clpa at some point, only once is important, but using get_clpa instead of the "import clpa" stuff, is something I completely agree with.
