### ISSUE TITLE
segment2clpa not aware of custom segments

### ISSUE THREAD

**Issue by LinguList** [glottobank/clpa#39]
https://github.com/glottobank/clpa/blob/master/pyclpa/base.py#L90-L93

Custom segments will be rendered with "?":

```python
CLPA.check_segment('5/')
"?"
```

**Comment by xrotwang** [comment]
The problem is a bit more involved:
```python
>>> from pyclpa.base import get_clpa
>>> CLPA = get_clpa()
>>> CLPA.check_sequence('5/')
([u'*5'], {u'5/': Sound(id=u'custom:5', clpa=u'*5', frequency=1, custom=True)}, Errors(convertible=0, non_convertible=0))
>>> CLPA.segment2clpa('*5')
u'?'
```
So, `check_sequence` is aware of the custom segments, but `segment2clpa` isn't. It is not fully clear what `segment2clpa` should do, but I think it should return some constant, maybe `*`?

In any case, we should turn these magic strings into proper package constants, i.e. have
```python
class CLPA(...):
    unknown = '?'
    custom = '*'
```

**Comment by LinguList** [comment]
Yes, I completely agree. This was again some adhoc coding from my side, but it needs to be properly documented and handled.

**Comment by xrotwang** [comment]
Is there a good reason why the whitelist is a JSON file, rather than a python `list` of `Sound` objects? Even if the reason is platform/language independence, I'd rather create the JSON from the python object periodically, than have to deal with the `dict` of `dict`s which the current internal representation  is.

**Comment by LinguList** [comment]
Actually, the json is created from the TSV file, as this is easiest to maintain. I'd not put sound objects into a python code, as this will become difficult to maintain (we have already more than 1000 segments), but I'm by no means against replacing the json by csv/tsv.

**Comment by xrotwang** [comment]
Is the TSV in the repository? I only see `clpa.test.tsv`.

**Comment by xrotwang** [comment]
Yeah, I think it would be better to read the original TSV in as `list` of proper objects that we can attach properties and methods to, thus bypassing/making obsolete the JSON.

**Comment by LinguList** [comment]
Yes, the clpa.test.tsv is the one. The reason why I was hesitating in touching these things is: we currently list basic "features" for each sound, and the goal is to have these being unique (a set of features defines a sound), but things like, e.g., the diphthongs are not satisfyinlgy defined, as are other things, and I'd like to talk with a phonetician at some point to see whether this system can be enhanced (maybe taking inspiration from Fonetikode). I'd also not be against getting rid of the strange identifiers, although I think we should NOT only use Unicode-Character combinations as identifiers, as it is possible that we want to change things at some point. So in brief: a real strategy on how to expand and maintain that list of characters is missing, due to gaps in my phonetic knowledge.

**Comment by xrotwang** [comment]
I think it's ok to leave out the feature system for the moment (on python side, I mean). The only thing we'd need right now for the maintenance of the TSV from my point of view are a few rules:
- IDs are unique
- CLPAs are unique (but may be changed)

Regarding the IDs: Is the naming scheme sound/useful? I.e. are we sure there won't be more than 999 of any of the TYPEs? Do we need the type abbreviation in the ID anyway? It would seem to make maintenance more difficult because figuring out the next ID is a bit more complicated.

**Comment by LinguList** [comment]
We could as well have consecutive numbers, which I find easiest to maintain, given that this will be manually edited. And yes: no need to keep the type info, this is just a column in the TSV, and also yes: we will run into issues with just 999 consonants (I'm afraid).

**Comment by xrotwang** [comment]
Ok. So here's my proposal:
- ditch the JSON
- instead go straight from TSV to proper objects in python, which have all the necessary logic, i.e. they know whether they are consonants, know how to compare and order, know how to be represented in unicode
- change IDs to consecutive integers

If we had this, we could also simplyfy `check_sequence` a lot, because it could simply return a `list` of these objects (plus `clpa.CUSTOM` and `clpa.UNKNOWN`), instead of the current `tokens, sounds, errors`. The `Sound` objects could have a property `converted` which could be set to the original symbol, so basically everything could be computed from the one returned list. Ideally, accents could be handled analogously, i.e. just be treated as something that can be converted to CLPA.

So we'd get something like
```python
>>> clpa.convert(['a', '.', '1/b', '1/'])
[<clpa.Sound 1>, <clpa.Unknown>, <clpa.Sound 2>, <clpa.Custom>]
```

**Comment by xrotwang** [comment]
And to continue:
```python
>>> ' '.join(['%s' % s for s in clpa.convert(['a', '.', '1/b', '1/'])])
'a ? b *'
```

**Comment by LinguList** [comment]
Wow, that looks beautiful!

**Comment by xrotwang** [comment]
I would use the [unicode replacement character](http://www.fileformat.info/info/unicode/char/fffd/index.htm) as default representation of `clpa.Unknown`, though. What do you think would be appropriate for `clpa.Custom`? Just whatever was left of `/`?

**Comment by xrotwang** [comment]
Oh, and the accent question again: Can accented things just be treated like stuff that can be converted to CLPA? The accent could always be recovered by comparing all instances of `clpa.Sound` with `converted==True` with the token in the sequence they correspond to. Alternatively, the any `clpa.Token` could store the sequence item it corresponds to.

**Comment by xrotwang** [comment]
So the latter proposal above would mean:
```python
>>> [s.origin for s in clpa.convert(['a', '.', '1/b', '1/'])] == ['a', '.', '1/b', '1/']
True
```

**Comment by LinguList** [comment]
> What do you think would be appropriate for clpa.Custom? Just whatever was left of /?

Yes, I guess that would be useful. This would be "h₂" in terms of laryngeals, etc.

And storing the "origin" is surely sufficient to solve the accent problem, with the great advantage that we can always get back.

**Comment by xrotwang** [comment]
So what was `errors.convertible` before would now simply be the number of sounds where `origin != clpa`? I.e. a sound would not have to know that it was converted from something accented as opposed to something aliased?

**Comment by LinguList** [comment]
Difficult to say: on the one hand, I'd really like to have some info on accents and the like (but also in lingpy, where they are not handled so far, but only ignored), on the other hand, I think it should be fine for now, and not very difficult to add it at another stage later on, right? Ideally at a point, when lingpy can finally handle accents on the prosodic strings, and we also have more data where accents are actually indicated.

**Comment by xrotwang** [comment]
Ok. Yes, I think it can be added later. Another question, though: What's the rationale behind the `rules` argument to `CLPA`? It seems to work much the same as `explicit`, but it is applied right in `check_sequence`, not in `find_token`. I would guess it should be removed.

**Comment by xrotwang** [comment]
And yet another question: The `delete` argument is now by default a list of ligatures, etc. Shouldn't this be removed as well? This would make the CLPA conversion a lot more transparent. Also the typical use case for CLPA would be **after** tokenization, and tokenizers will presumably already provide a way to deal with these things.

**Comment by LinguList** [comment]
Yes, I guess it should be fine to delete the ligatures as well. Given that we discussed anyway to spell out also things like the "patterns.tsv" (which could then all be placed into "explicit.tsv"), the same can be done with the ligature things.
